# baseURL = 'https://xichenlab.com/'
baseURL = 'https://dbrg77.github.io/lab-website/'
languageCode = 'en-gb'
title = 'Xi Chen Lab @ SUSTech'
theme = "hugo-theme-monochrome"
enableRobotsTXT = true
canonifyurls = true
publishDir = "/Users/xichen/Documents/lab_website_build"

[params]
  enable_toc = false
  enable_math = true
  footer = "Xi Chen Lab @ SUSTech, 2024"

[menu]
  [[menu.navbar]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  
  [[menu.navbar]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 2

    [[menu.navbar]]
    identifier = "teaching"
    name = "Teaching"
    url = "/teaching/"
    weight = 3

  [[menu.navbar]]
    identifier = "members"
    name = "Members"
    url = "/members/"
    weight = 4
  
  [[menu.navbar]]
    identifier = "posts"
    name = "BehindThePaper"
    url = "/posts/"
    weight = 10
  
  [[menu.navbar]]
    identifier = "publication"
    name = "Publications"
    url = "/publications/"
    weight = 20
  
  [[menu.navbar]]
    identifier = "resource"
    name = "Resource"
    url = "/resource/"
    weight = 30
  
  [[menu.navbar]]
    identifier = "newsphotos"
    name = "News & Photos"
    url = "/news/"
    weight = 40

  [[menu.navbar]]
    identifier = "joinus"
    name = "Join Us"
    url = "/joinus/"
    weight = 50

[caches]
  [caches.images]
    dir = ':cacheDir/images'
